services:
  - type: web
    name: fruit-veg-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
    runtime: python-3.9
